"""
Generic OAuth2 helpers: state generation, CSRF validation, authorization URL
construction, and authorization-code exchange.

All network I/O is async (httpx.AsyncClient).  Secrets are read from the
Settings object passed in — never from module-level globals — so this module
is safe to import in tests without real env vars.
"""

import secrets
from dataclasses import dataclass, field
from typing import TYPE_CHECKING
from urllib.parse import urlencode

import httpx

from app.auth.providers import PROVIDERS

if TYPE_CHECKING:
    from app.config import Settings


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class OAuthError(Exception):
    """Raised when an OAuth2 flow step fails (network, server error, etc.)."""


class OAuthStateError(OAuthError):
    """Raised when the CSRF state token is missing or does not match."""


# ---------------------------------------------------------------------------
# Frozen response DTO
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class TokenResponse:
    """Parsed OAuth2 token endpoint response."""

    access_token: str
    token_type: str
    refresh_token: str | None = field(default=None)
    expires_in: int | None = field(default=None)
    scope: str | None = field(default=None)


# ---------------------------------------------------------------------------
# State helpers
# ---------------------------------------------------------------------------


def generate_state() -> str:
    """Return a cryptographically random URL-safe state token (32+ chars)."""
    return secrets.token_urlsafe(32)


def validate_state(*, expected: str, actual: str) -> None:
    """Assert *actual* matches *expected*.

    Uses constant-time comparison to prevent timing attacks.

    Raises:
        OAuthStateError: if either value is empty or they do not match.
    """
    if not expected or not actual:
        raise OAuthStateError("OAuth state is missing")
    if not secrets.compare_digest(expected, actual):
        raise OAuthStateError("OAuth state mismatch — possible CSRF attack")


# ---------------------------------------------------------------------------
# Authorization URL
# ---------------------------------------------------------------------------


def build_authorization_url(
    provider_name: str,
    *,
    state: str,
    settings: "Settings",
) -> str:
    """Build the redirect URL that sends the user to the provider's login page.

    Args:
        provider_name: One of the keys in PROVIDERS (e.g. "github").
        state:         CSRF token generated by generate_state().
        settings:      App settings holding client_id and redirect_uri.

    Raises:
        KeyError:   if *provider_name* is not in PROVIDERS.
    """
    provider = PROVIDERS[provider_name]  # raises KeyError for unknown providers

    client_id, redirect_uri = _provider_credentials(provider_name, settings)

    params: dict[str, str] = {
        "client_id": client_id,
        "redirect_uri": redirect_uri,
        "state": state,
        "response_type": "code",
    }
    if provider.scopes:
        params["scope"] = " ".join(provider.scopes)

    # Notion requires owner=user for workspace-level authorization
    if provider_name == "notion":
        params["owner"] = "user"

    return f"{provider.auth_url}?{urlencode(params)}"


# ---------------------------------------------------------------------------
# Code exchange
# ---------------------------------------------------------------------------


async def exchange_code(
    provider_name: str,
    *,
    code: str,
    settings: "Settings",
) -> TokenResponse:
    """Exchange an authorization code for tokens.

    Args:
        provider_name: One of the keys in PROVIDERS.
        code:          The authorization code from the callback.
        settings:      App settings holding client credentials.

    Returns:
        TokenResponse with access_token (and optionally refresh_token).

    Raises:
        OAuthError: on HTTP errors or provider-level error responses.
    """
    provider = PROVIDERS[provider_name]
    client_id, redirect_uri = _provider_credentials(provider_name, settings)
    client_secret = _provider_secret(provider_name, settings)

    payload = {
        "client_id": client_id,
        "client_secret": client_secret,
        "code": code,
        "redirect_uri": redirect_uri,
        "grant_type": "authorization_code",
    }

    headers = {"Accept": "application/json"}

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                provider.token_url,
                data=payload,
                headers=headers,
                timeout=10.0,
            )
            response.raise_for_status()
    except httpx.HTTPStatusError as exc:
        raise OAuthError(
            f"Token exchange HTTP error {exc.response.status_code} for {provider_name}"
        ) from exc
    except httpx.RequestError as exc:
        raise OAuthError(f"Token exchange request failed for {provider_name}") from exc

    body = response.json()

    if "error" in body:
        raise OAuthError(
            f"Token exchange error for {provider_name}: "
            f"{body.get('error')} — {body.get('error_description', '')}"
        )

    return TokenResponse(
        access_token=body["access_token"],
        token_type=body.get("token_type", "bearer"),
        refresh_token=body.get("refresh_token"),
        expires_in=body.get("expires_in"),
        scope=body.get("scope"),
    )


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _provider_credentials(provider_name: str, settings: "Settings") -> tuple[str, str]:
    """Return (client_id, redirect_uri) for *provider_name*."""
    if provider_name == "github":
        return settings.github_client_id, settings.github_oauth_redirect_uri
    if provider_name == "notion":
        return settings.notion_client_id, settings.notion_oauth_redirect_uri
    if provider_name == "linkedin":
        return settings.linkedin_client_id, settings.linkedin_oauth_redirect_uri
    raise ValueError(f"Unknown provider: {provider_name!r}")


def _provider_secret(provider_name: str, settings: "Settings") -> str:
    """Return the plaintext client_secret for *provider_name*."""
    if provider_name == "github":
        return settings.github_client_secret.get_secret_value()
    if provider_name == "notion":
        return settings.notion_client_secret.get_secret_value()
    if provider_name == "linkedin":
        return settings.linkedin_client_secret.get_secret_value()
    raise ValueError(f"Unknown provider: {provider_name!r}")
